sudo: required
language: java
jdk: openjdk15
services:
  - docker
branches:
  only:
    - master
    - /^feature/.*$/
cache:
  directories:
    - $home/.m2/repository
script: mvn clean package
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y gpgv
  - docker build -t bluezdrive/kafka-cluster-deployment-service:1.0 ./kafka-cluster-deployment-service/
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: mvn dockerfile:build dockerfile:push
#    on:
#      branch: master
