sudo: required
language: java
jdk: openjdk15
branches:
  only:
    - master
    - /^feature/.*$/
cache:
  directories:
    - $home/.m2/repository
script: mvn clean package
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    skip_cleanup: true
    script: mvn dockerfile:build dockerfile:push
    on:
      branch: master
