server:
  servlet:
    session:
      persistent: false
management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, auditevents, prometheus, logfile, metrics
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      "[hibernate.generate_statistics]": true
logging:
  file:
    name: logs/kcds.log
  level:
    root: info
    org.hibernate: warn
info:
  app:
    name: Apache Kafka Cluster Deployment
    description: A deployment server for Apache Kafka Cluster and Schema Registry

